-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 00:37:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Email` VARCHAR(100) NULL,
  `Sena` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `ImgUsua` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consultas` (
  `idConsultas` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Fecha` DATE NULL,
  `Horario` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(80) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idConsultas`, `Usuario_idUsuario`),
  CONSTRAINT `fk_Consultas_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesionales` (
  `idProfesionales` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Formacion` VARCHAR(150) NULL,
  `ImgProf` VARCHAR(45) NULL,
  `Consultas_idConsultas` INT NOT NULL,
  `Consultas_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProfesionales`, `Consultas_idConsultas`, `Consultas_Usuario_idUsuario`),
  CONSTRAINT `fk_Profesionales_Consultas1`
    FOREIGN KEY (`Consultas_idConsultas` , `Consultas_Usuario_idUsuario`)
    REFERENCES `mydb`.`Consultas` (`idConsultas` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias` (
  `idNoticias` INT NOT NULL,
  `Titulo` VARCHAR(50) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgNoti` VARCHAR(45) NULL,
  `Profesionales_idProfesionales` INT NOT NULL,
  `Profesionales_Consultas_idConsultas` INT NOT NULL,
  `Profesionales_Consultas_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNoticias`, `Profesionales_idProfesionales`, `Profesionales_Consultas_idConsultas`, `Profesionales_Consultas_Usuario_idUsuario`),
   CONSTRAINT `fk_Noticias_Profesionales1`
    FOREIGN KEY (`Profesionales_idProfesionales` , `Profesionales_Consultas_idConsultas` , `Profesionales_Consultas_Usuario_idUsuario`)
    REFERENCES `mydb`.`Profesionales` (`idProfesionales` , `Consultas_idConsultas` , `Consultas_Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consejos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consejos` (
  `idConsejos` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgCons` VARCHAR(45) NULL,
  `Profesionales_idProfesionales` INT NOT NULL,
  `Profesionales_Consultas_idConsultas` INT NOT NULL,
  `Profesionales_Consultas_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idConsejos`, `Profesionales_idProfesionales`, `Profesionales_Consultas_idConsultas`, `Profesionales_Consultas_Usuario_idUsuario`),
  CONSTRAINT `fk_Consejos_Profesionales1`
    FOREIGN KEY (`Profesionales_idProfesionales` , `Profesionales_Consultas_idConsultas` , `Profesionales_Consultas_Usuario_idUsuario`)
    REFERENCES `mydb`.`Profesionales` (`idProfesionales` , `Consultas_idConsultas` , `Consultas_Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `idServicios` INT NOT NULL,
  `Servicio` VARCHAR(100) NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  `ImgServ` VARCHAR(45) NULL,
  PRIMARY KEY (`idServicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesionales_has_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesionales_has_Servicios` (
  `Profesionales_idProfesionales` INT NOT NULL,
  `Profesionales_Consultas_idConsultas` INT NOT NULL,
  `Profesionales_Consultas_Usuario_idUsuario` INT NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`Profesionales_idProfesionales`, `Profesionales_Consultas_idConsultas`, `Profesionales_Consultas_Usuario_idUsuario`, `Servicios_idServicios`),
  CONSTRAINT `fk_Profesionales_has_Servicios_Profesionales1`
    FOREIGN KEY (`Profesionales_idProfesionales` , `Profesionales_Consultas_idConsultas` , `Profesionales_Consultas_Usuario_idUsuario`)
    REFERENCES `mydb`.`Profesionales` (`idProfesionales` , `Consultas_idConsultas` , `Consultas_Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesionales_has_Servicios_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `mydb`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenCons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenCons` (
  `idImagenCons` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenCons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenProf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenProf` (
  `idImagenProf` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenProf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenNoti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenNoti` (
  `idImagenNoti` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenNoti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenServ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenServ` (
  `idImagenServ` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenServ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios_has_ImagenServ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios_has_ImagenServ` (
  `Servicios_idServicios` INT NOT NULL,
  `ImagenServ_idImagenServ` INT NOT NULL,
  PRIMARY KEY (`Servicios_idServicios`, `ImagenServ_idImagenServ`),
  CONSTRAINT `fk_Servicios_has_ImagenServ_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `mydb`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicios_has_ImagenServ_ImagenServ1`
    FOREIGN KEY (`ImagenServ_idImagenServ`)
    REFERENCES `mydb`.`ImagenServ` (`idImagenServ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias_has_ImagenNoti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias_has_ImagenNoti` (
  `Noticias_idNoticias` INT NOT NULL,
  `Noticias_Profesionales_idProfesionales` INT NOT NULL,
  `Noticias_Profesionales_Consultas_idConsultas` INT NOT NULL,
  `Noticias_Profesionales_Consultas_Usuario_idUsuario` INT NOT NULL,
  `ImagenNoti_idImagenNot` INT NOT NULL,
  PRIMARY KEY (`Noticias_idNoticias`, `Noticias_Profesionales_idProfesionales`, `Noticias_Profesionales_Consultas_idConsultas`, `Noticias_Profesionales_Consultas_Usuario_idUsuario`, `ImagenNoti_idImagenNot`),
  CONSTRAINT `fk_Noticias_has_ImagenNoti_Noticias1`
    FOREIGN KEY (`Noticias_idNoticias` , `Noticias_Profesionales_idProfesionales` , `Noticias_Profesionales_Consultas_idConsultas` , `Noticias_Profesionales_Consultas_Usuario_idUsuario`)
    REFERENCES `mydb`.`Noticias` (`idNoticias` , `Profesionales_idProfesionales` , `Profesionales_Consultas_idConsultas` , `Profesionales_Consultas_Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noticias_has_ImagenNoti_ImagenNoti1`
    FOREIGN KEY (`ImagenNoti_idImagenNot`)
    REFERENCES `mydb`.`ImagenNoti` (`idImagenNoti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consejos_has_ImagenCons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consejos_has_ImagenCons` (
  `Consejos_idConsejos` INT NOT NULL,
  `Consejos_Profesionales_idProfesionales` INT NOT NULL,
  `Consejos_Profesionales_Consultas_idConsultas` INT NOT NULL,
  `Consejos_Profesionales_Consultas_Usuario_idUsuario` INT NOT NULL,
  `ImagenCons_idImagenCons` INT NOT NULL,
  PRIMARY KEY (`Consejos_idConsejos`, `Consejos_Profesionales_idProfesionales`, `Consejos_Profesionales_Consultas_idConsultas`, `Consejos_Profesionales_Consultas_Usuario_idUsuario`, `ImagenCons_idImagenCons`),
  CONSTRAINT `fk_Consejos_has_ImagenCons_Consejos1`
    FOREIGN KEY (`Consejos_idConsejos` , `Consejos_Profesionales_idProfesionales` , `Consejos_Profesionales_Consultas_idConsultas` , `Consejos_Profesionales_Consultas_Usuario_idUsuario`)
    REFERENCES `mydb`.`Consejos` (`idConsejos` , `Profesionales_idProfesionales` , `Profesionales_Consultas_idConsultas` , `Profesionales_Consultas_Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consejos_has_ImagenCons_ImagenCons1`
    FOREIGN KEY (`ImagenCons_idImagenCons`)
    REFERENCES `mydb`.`ImagenCons` (`idImagenCons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesionales_has_ImagenProf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesionales_has_ImagenProf` (
  `Profesionales_idProfesionales` INT NOT NULL,
  `Profesionales_Consultas_idConsultas` INT NOT NULL,
  `Profesionales_Consultas_Usuario_idUsuario` INT NOT NULL,
  `ImagenProf_idImagenProf` INT NOT NULL,
  PRIMARY KEY (`Profesionales_idProfesionales`, `Profesionales_Consultas_idConsultas`, `Profesionales_Consultas_Usuario_idUsuario`, `ImagenProf_idImagenProf`),
  CONSTRAINT `fk_Profesionales_has_ImagenProf_Profesionales1`
    FOREIGN KEY (`Profesionales_idProfesionales` , `Profesionales_Consultas_idConsultas` , `Profesionales_Consultas_Usuario_idUsuario`)
    REFERENCES `mydb`.`Profesionales` (`idProfesionales` , `Consultas_idConsultas` , `Consultas_Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesionales_has_ImagenProf_ImagenProf1`
    FOREIGN KEY (`ImagenProf_idImagenProf`)
    REFERENCES `mydb`.`ImagenProf` (`idImagenProf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
