-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 00:21:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Email` VARCHAR(100) NULL,
  `Sena` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `FotoUsu` VARCHAR(45) NULL)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Noticias` (
  `idNoticias` INT NOT NULL,
  `Titulo` VARCHAR(50) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgNot` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Consultas` (
  `idConsultas` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Fecha` DATE NULL,
  `Horario` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(80) NULL,
  `Usuario_idUsuario` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consejos`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Consejos` (
  `idConsejos` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgCons` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesionales`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Profesionales` (
  `idProfesionales` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Formacion` VARCHAR(150) NULL,
  `FotoProf` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Servicios` (
  `idServicios` INT NOT NULL,
  `Servicio` VARCHAR(100) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgSer` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenCons`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`ImagenCons` (
  `idImagenCons` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenProf`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`ImagenProf` (
  `idImagenProf` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenNoti`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`ImagenNoti` (
  `idImagenNoti` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenServ`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`ImagenServ` (
  `idImagenServ` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Slide`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Slide` (
  `idSlide` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias_has_ImagenNoti`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Noticias_has_ImagenNoti` (
  `Noticias_idNoticias` INT NOT NULL,
  `Noticias_Usuario_idUsuario` INT NOT NULL,
  `ImagenNoti_idImagenNoti` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios_has_ImagenServ`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Servicios_has_ImagenServ` (
  `Servicios_idServicios` INT NOT NULL,
  `Servicios_Usuario_idUsuario` INT NOT NULL,
  `ImagenServ_idImagenServ` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesionales_has_ImagenProf`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Profesionales_has_ImagenProf` (
  `Profesionales_idProfesionales` INT NOT NULL,
  `Profesionales_Usuario_idUsuario` INT NOT NULL,
  `ImagenProf_idImagenProf` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consejos_has_ImagenCons`
-- -----------------------------------------------------
CREATE TABLE `mydb`.`Consejos_has_ImagenCons` (
  `Consejos_idConsejos` INT NOT NULL,
  `Consejos_Usuario_idUsuario` INT NOT NULL,
  `ImagenCons_idImagenCons` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
