-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 23:26:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(100) NULL,
  `Sena` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `FotoUsu` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias` (
  `idNoticias` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(50) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgNot` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNoticias`, `Usuario_idUsuario`),
  INDEX `fk_Noticias_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Noticias_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consultas` (
  `idConsultas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Fecha` DATE NULL,
  `Horario` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(80) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idConsultas`, `Usuario_idUsuario`),
  INDEX `fk_Consultas_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Consultas_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consejos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consejos` (
  `idConsejos` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgCons` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idConsejos`, `Usuario_idUsuario`),
  INDEX `fk_Consejos_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Consejos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesionales` (
  `idProfesionales` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Formacion` VARCHAR(150) NULL,
  `FotoProf` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProfesionales`, `Usuario_idUsuario`),
  INDEX `fk_Profesionales_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Profesionales_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `idServicios` INT NOT NULL AUTO_INCREMENT,
  `Servicio` VARCHAR(100) NULL,
  `Descripcion` VARCHAR(500) NULL,
  `ImgSer` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idServicios`, `Usuario_idUsuario`),
  INDEX `fk_Servicios_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Servicios_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenCons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenCons` (
  `idImagenCons` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenCons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenProf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenProf` (
  `idImagenProf` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenProf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenNoti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenNoti` (
  `idImagenNoti` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenNoti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ImagenServ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ImagenServ` (
  `idImagenServ` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idImagenServ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Slide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Slide` (
  `idSlide` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Imagen` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSlide`, `Usuario_idUsuario`),
  INDEX `fk_Slide_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Slide_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias_has_ImagenNoti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias_has_ImagenNoti` (
  `Noticias_idNoticias` INT NOT NULL AUTO_INCREMENT,
  `Noticias_Usuario_idUsuario` INT NOT NULL,
  `ImagenNoti_idImagenNoti` INT NOT NULL,
  PRIMARY KEY (`Noticias_idNoticias`, `Noticias_Usuario_idUsuario`, `ImagenNoti_idImagenNoti`),
  INDEX `fk_Noticias_has_ImagenNoti_ImagenNoti1_idx` (`ImagenNoti_idImagenNoti` ASC) VISIBLE,
  INDEX `fk_Noticias_has_ImagenNoti_Noticias1_idx` (`Noticias_idNoticias` ASC, `Noticias_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Noticias_has_ImagenNoti_Noticias1`
    FOREIGN KEY (`Noticias_idNoticias` , `Noticias_Usuario_idUsuario`)
    REFERENCES `mydb`.`Noticias` (`idNoticias` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noticias_has_ImagenNoti_ImagenNoti1`
    FOREIGN KEY (`ImagenNoti_idImagenNoti`)
    REFERENCES `mydb`.`ImagenNoti` (`idImagenNoti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios_has_ImagenServ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios_has_ImagenServ` (
  `Servicios_idServicios` INT NOT NULL AUTO_INCREMENT,
  `Servicios_Usuario_idUsuario` INT NOT NULL,
  `ImagenServ_idImagenServ` INT NOT NULL,
  PRIMARY KEY (`Servicios_idServicios`, `Servicios_Usuario_idUsuario`, `ImagenServ_idImagenServ`),
  INDEX `fk_Servicios_has_ImagenServ_ImagenServ1_idx` (`ImagenServ_idImagenServ` ASC) VISIBLE,
  INDEX `fk_Servicios_has_ImagenServ_Servicios1_idx` (`Servicios_idServicios` ASC, `Servicios_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Servicios_has_ImagenServ_Servicios1`
    FOREIGN KEY (`Servicios_idServicios` , `Servicios_Usuario_idUsuario`)
    REFERENCES `mydb`.`Servicios` (`idServicios` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicios_has_ImagenServ_ImagenServ1`
    FOREIGN KEY (`ImagenServ_idImagenServ`)
    REFERENCES `mydb`.`ImagenServ` (`idImagenServ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesionales_has_ImagenProf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesionales_has_ImagenProf` (
  `Profesionales_idProfesionales` INT NOT NULL AUTO_INCREMENT,
  `Profesionales_Usuario_idUsuario` INT NOT NULL,
  `ImagenProf_idImagenProf` INT NOT NULL,
  PRIMARY KEY (`Profesionales_idProfesionales`, `Profesionales_Usuario_idUsuario`, `ImagenProf_idImagenProf`),
  INDEX `fk_Profesionales_has_ImagenProf_ImagenProf1_idx` (`ImagenProf_idImagenProf` ASC) VISIBLE,
  INDEX `fk_Profesionales_has_ImagenProf_Profesionales1_idx` (`Profesionales_idProfesionales` ASC, `Profesionales_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Profesionales_has_ImagenProf_Profesionales1`
    FOREIGN KEY (`Profesionales_idProfesionales` , `Profesionales_Usuario_idUsuario`)
    REFERENCES `mydb`.`Profesionales` (`idProfesionales` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesionales_has_ImagenProf_ImagenProf1`
    FOREIGN KEY (`ImagenProf_idImagenProf`)
    REFERENCES `mydb`.`ImagenProf` (`idImagenProf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consejos_has_ImagenCons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consejos_has_ImagenCons` (
  `Consejos_idConsejos` INT NOT NULL AUTO_INCREMENT,
  `Consejos_Usuario_idUsuario` INT NOT NULL,
  `ImagenCons_idImagenCons` INT NOT NULL,
  PRIMARY KEY (`Consejos_idConsejos`, `Consejos_Usuario_idUsuario`, `ImagenCons_idImagenCons`),
  INDEX `fk_Consejos_has_ImagenCons_ImagenCons1_idx` (`ImagenCons_idImagenCons` ASC) VISIBLE,
  INDEX `fk_Consejos_has_ImagenCons_Consejos1_idx` (`Consejos_idConsejos` ASC, `Consejos_Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Consejos_has_ImagenCons_Consejos1`
    FOREIGN KEY (`Consejos_idConsejos` , `Consejos_Usuario_idUsuario`)
    REFERENCES `mydb`.`Consejos` (`idConsejos` , `Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consejos_has_ImagenCons_ImagenCons1`
    FOREIGN KEY (`ImagenCons_idImagenCons`)
    REFERENCES `mydb`.`ImagenCons` (`idImagenCons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nosotros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nosotros` (
  `idNosotros` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(700) NULL,
  `Imagen` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNosotros`, `Usuario_idUsuario`),
  INDEX `fk_Nosotros_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Nosotros_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
